### ISSUE TITLE
Is not support region `tyo3`?

### ISSUE THREAD

**Issue by kimjayney** [hironobu-s/conoha-iso#3]
I can't use conoha-iso -i https://endpoint.com/windows.iso 
it displays `ERRO[0000] Undefined region[tyo3].`

Also I tried changed go source in `api.go` 
TYO2 = "tyo2" -> TYO2 = "tyo3" 
and I compiled conoha-iso but it displays another error like 
```
ERRO[0000] Return 404 status code from the server. (<html><body><h1>404 Not Found</h1>
The requested resource could not be found.
</body></html>
```

It seems tyo3 region is not support for this method. 
How can I use tyo3 region for Custom ISO?

**Comment by hironobu-s** [comment]
@kimjayney 
I have yet to use any VPS in tyo3. If you get the 404 error status from APIs, there is no way to mount/unmount your ISO image to the VPS in that region.

**Comment by kimjayney** [comment]
ok

**Comment by kimjayney** [comment]
Can I change region?
